Repository pmndrs/react-spring, pull requests merged in 2021-04, with the labels that each got.

#1395 [fix] Event API unification based on useTransition
  .codesandbox/ci.json
  demo/src/sandboxes/notification-hub/package.json
  demo/src/sandboxes/notification-hub/src/App.tsx
  demo/src/sandboxes/notification-hub/src/styles.ts
  demo/src/sandboxes/tree/src/styles.ts
  demo/yarn.lock
  packages/core/src/AnimationResult.ts
  packages/core/src/Controller.test.ts
  packages/core/src/Controller.ts
  packages/core/src/SpringValue.ts
  packages/core/src/hooks/useTransition.tsx
  packages/core/src/runAsync.ts
  packages/core/src/types/functions.ts
  packages/core/src/types/internal.ts
  packages/core/src/types/objects.ts
  packages/core/src/types/props.ts
  packages/core/src/types/transition.ts
Labels: bug

#1384 [fix] skip animation with async to infinite loop
  packages/core/src/Controller.test.ts
  packages/core/src/runAsync.ts
  packages/core/test/setup.ts
Labels: bug

#1378 [fix] Stop jank in animation when duration changes on SpringValue
  packages/animated/src/AnimatedValue.ts
  packages/core/src/SpringValue.ts
Labels: bug

#1387 fix: make SpringRef instances callable to avoid breaking change #1359
  demo/src/sandboxes/goo-blobs/src/App.tsx
  demo/src/sandboxes/notification-hub/src/App.tsx
  packages/core/src/SpringRef.ts
  packages/core/src/types/props.ts
  packages/shared/src/deprecations.ts
Labels: enhancement

#1460 Fix: Ignore partial color names when interpolating strings.
  packages/shared/src/createInterpolator.test.ts
  packages/shared/src/stringInterpolation.ts
Labels: bug, v9
